apiVersion: v1
kind: Service
metadata:
  name: alertmanager-gchat
  namespace: monitoring
spec:
  selector:
    app: alertmanager-gchat
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http
